### ISSUE TITLE
deploy broken since 2023-02-06

### ISSUE THREAD

**Issue by benbai123** [hmanzur/actions-aws-eb#10]
Please refer to this issue [Deploy to aws broken after 2023-02-04](https://github.com/actions/runner-images/issues/7049)

The workaround is add a command `git config --global --add safe.directory /github/workspace` and `hmanzur/actions-aws-eb` create its own container, could you add this command into Dockerfile?

Or if there are any other solutions?

Thanks.

**Comment by benbai123** [comment]
closed since problem solved

**Comment by YevgenyAnanin** [comment]
@benbai123 could you please elaborate how you solved the problem?  Where exactly did you add the command
```
git config --global --add safe.directory /github/workspace
```
?

My deployments are broken right now, so thanks in advance for any suggestions!

**Comment by jlozano254** [comment]
@YevgenyAnanin Same issue here, I've already tried several commands with no success...

It seems that the actions runs inside docker, so maybe we need to add that workaround inside entrypoint.sh example: https://github.com/surefyresystems/actions-aws-eb/commit/03eb377f9072bb0416f44e71d9d3ec835b8defdd

**Comment by benbai123** [comment]
@YevgenyAnanin I solved it by deploy with zip file by another tool actions/beanstalk-deploy.

**Comment by rdlabo** [comment]
> @YevgenyAnanin Same issue here, I've already tried several commands with no success...
> 
> It seems that the actions runs inside docker, so maybe we need to add that workaround inside entrypoint.sh example: [surefyresystems@03eb377](https://github.com/surefyresystems/actions-aws-eb/commit/03eb377f9072bb0416f44e71d9d3ec835b8defdd)

This method is success. I changed resource:

```
      - name: Deploy to EB
        uses: surefyresystems/actions-aws-eb@master
```
